// front_end-frameworks/svelte/src/components/ui/Brand.svelte
<script>
  import { Brain } from '@lucide/svelte'

  let { className = "" } = $props();
</script>

<div class="flex items-center gap-2 {className}">
  <div class="bg-violet-500 p-1 rounded-lg text-white text-xs">
    <Brain aria-hidden="true" />
  </div>
  <span class="text-white font-bold">Agentic AI</span>
</div>

// front_end-frameworks/react/src/components/ui/Brand.jsx
import { Brain } from 'lucide-react';

function Brand({ className= "" }) {
    return (
        <div className={`flex items-center gap-2 ${className}`}>
            <div className="bg-violet-500 p-1 rounded-lg text-white text-xs">
                <Brain aria-hidden="true"  />
            </div>
            <span className="text-white font-bold">Agentic AI</span>
        </div>
    )
}
export default Brand
