// front_end-frameworks/vue/src/components/ui/SectionTitle.vue
<script setup>
defineProps({
  line1: { type: String, required: true },
  line2: { type: String, required: true },
})
</script>

<template>
  <h2 class="mb-8 text-4xl md:text-5xl font-black tracking-tight leading-none">
    <span class="block text-white">{{ line1 }}</span>
    <span class="block text-violet-300">{{ line2 }}</span>
  </h2>
</template>

// front_end-frameworks/react/src/components/ui/SectionTitle.jsx
function SectionTitle ({line1, line2}) {
    return (
            <h2 className="mb-8 text-4xl md:text-5xl font-black tracking-tight leading-none">
                <span className="block text-white">{line1}</span>
                <span className="block text-violet-300">{line2}</span>
            </h2>
    )
}
export default SectionTitle
