// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from './components/layout/Header.svelte'
  import Hero from './components/sections/Hero.svelte'
  import About from './components/sections/About.svelte'
  import Features from './components/sections/Features.svelte'
  import Insights from './components/sections/Insights.svelte'
  import Contact from './components/sections/Contact.svelte'
  import Footer from './components/layout/Footer.svelte'
</script>

  <Header />
  <main class="pt-18">
    <Hero />
    <About />
    <Features />
    <Insights />
    <Contact />
  </main>
<Footer />

// front_end-frameworks/react/src/App.jsx
import Header from './components/layout/Header'
import Hero from './components/sections/Hero'
import About from './components/sections/About'
import Features from './components/sections/Features'
import Insights from './components/sections/Insights'
import Contact from './components/sections/Contact'
import Footer from './components/layout/Footer'

function App() {
  return (
    <>
      <Header />
      <main className="pt-18">
        <Hero />
        <About />
        <Features />
        <Insights />
        <Contact />
      </main>
      <Footer />
    </>
  )
}

export default App
