// front_end-frameworks/vue/src/components/ui/Brand.vue
<script setup>
import { Brain } from 'lucide-vue-next'
</script>

<template>
  <div class="flex items-center gap-2">
    <div class="bg-violet-500 p-1 rounded-lg text-white text-xs">
      <Brain aria-hidden="true" />
    </div>
    <span class="text-white font-bold">Agentic AI</span>
  </div>
</template>

// front_end-frameworks/svelte/src/components/ui/Brand.svelte
<script>
  import { Brain } from '@lucide/svelte'

  let { className = "" } = $props();
</script>

<div class="flex items-center gap-2 {className}">
  <div class="bg-violet-500 p-1 rounded-lg text-white text-xs">
    <Brain aria-hidden="true" />
  </div>
  <span class="text-white font-bold">Agentic AI</span>
</div>
